export component HomeView inherits VerticalLayout {
    padding: 40px;
    alignment: center;
    spacing: 20px;

    Text {
        text: "🏠 ROZCESTNÍK";
        color: white;
        font-size: 32px;
        font-weight: 800;
        horizontal-alignment: center;
    }
    Text {
        text: "Vítejte v systému. Vyberte akci v levém menu.";
        color: #888;
        horizontal-alignment: center;
    }
}