export component SettingsView inherits VerticalLayout {
    padding: 40px;
    alignment: center;
    spacing: 20px;

    Text {
        text: "⚙ NASTAVENÍ";
        color: white;
        font-size: 32px;
        font-weight: 800;
        horizontal-alignment: center;
    }
    Text {
        text: "Konfigurace cest k serveru a uživatelské preference.";
        color: #888;
        horizontal-alignment: center;
    }
}