import { Sidebar } from "components/sidebar.slint";
import { HomeView } from "views/home.slint";
import { ImportView } from "views/import.slint";
import { SettingsView } from "views/settings.slint";

export component AppWindow inherits Window {
    title: "MRB Obchodník";
    preferred-width: 1300px;
    preferred-height: 850px;
    background: #1A1A1A;

    in property <string> verze_aplikace: "0.1.2";
    in-out property <int> vybrany_index: 0;
    
    property <int> rezim_prace: 0;
    property <color> barva_stranky: rezim_prace == 1 ? #f39c12 : (rezim_prace == 2 ? #27ae60 : #4aa3df);
    property <string> titulek_stranky: rezim_prace == 1 ? "POPTÁVKA" : (rezim_prace == 2 ? "OBJEDNÁVKA" : "IMPORT");

    in property <int> db_status_code: 1;
    in property <string> stav_text: "NAČÍTÁNÍ...";
    in property <string> posledni_sync: "Neznámý";
    in property <int> pocet_celkem: 0;
    in property <int> pocet_chybi: 0;

    in property <string> path_tech_docs: "";
    in property <string> path_production: "";
    in property <string> path_offers: "";

    in property <bool> show_progress: false;
    in property <float> progress_value: 0.0;
    in property <string> progress_label: "";

    callback vybrat-soubor-databaze();
    callback change-tech-docs();
    callback change-production();
    callback change-offers();

    HorizontalLayout {
        Sidebar {
            aktivni-stranka <=> root.vybrany_index;
            akcent-barva: root.barva_stranky;
            verze-aplikace: root.verze_aplikace;
        }

        Rectangle {
            horizontal-stretch: 1;

            if (root.vybrany_index == 0) : HomeView {
                nabidka-vybrana => { root.rezim_prace = 1; root.vybrany_index = 1; }
                objednavka-vybrana => { root.rezim_prace = 2; root.vybrany_index = 1; }
            }
            
            if (root.vybrany_index == 1) : ImportView {
                akcent-barva: root.barva_stranky;
                nazev-rezimu: root.titulek_stranky;
            }

            if (root.vybrany_index == 2) : SettingsView {
                db-status-code: root.db_status_code;
                stav-text: root.stav_text;
                posledni-sync: root.posledni_sync;
                pocet-celkem: root.pocet_celkem;
                pocet-chybi: root.pocet_chybi;

                path-tech-docs: root.path_tech_docs;
                path-production: root.path_production;
                path-offers: root.path_offers;

                show-progress: root.show_progress;
                progress-value: root.progress_value;
                progress-label: root.progress_label;

                vybrat-soubor-databaze => { root.vybrat-soubor-databaze(); }
                change-tech-docs => { root.change-tech-docs(); }
                change-production => { root.change-production(); }
                change-offers => { root.change-offers(); }
            }
        }
    }
}