import { Sidebar } from "components/sidebar.slint";

import { HomeView } from "views/home.slint";
import { ImportView } from "views/import.slint";
import { SettingsView } from "views/settings.slint";

export component AppWindow inherits Window {
    title: "MRB Obchodník - Nový Projekt";
    min-width: 1100px;
    min-height: 750px;
    background: #1A1A1A; // Původní barva pozadí okna

    in-out property <int> vybrany_index: 0;
    

    HorizontalLayout {
        padding: 0;
        spacing: 0;

        // Volání našeho samostatného komponentu
        Sidebar {
            akcent-barva: #4aa3df;
            verze-aplikace: "0.5.0";
            aktivni-stranka <=> root.vybrany_index;        
        }

        // Hlavní pracovní plocha (zatím prázdná)
        VerticalLayout {
            Rectangle {
            horizontal-stretch: 1;
            background: #1a1a1a;

            // Slint automaticky zobrazí pouze ten komponent, jehož podmínka platí
            if (root.vybrany_index == 0) : HomeView {}
            if (root.vybrany_index == 1) : ImportView {}
            if (root.vybrany_index == 2) : SettingsView {}
            }
        }
    }
}
